### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by whitef0x0** [tellform/tellform#331]
I'm still getting a lot of requests and have not been able to fulfill them or work on TellForm due to other commitments.

Currently looking for maintainers to take over this project.

**Comment by lalop** [comment]
hello @whitef0x0 I'm afraid I do not have enough free time to maintain tellform.
I hope that you will find someone

**Comment by Leopere** [comment]
I only want to get the Docker stuff working but I could help to some degree.  Mainly I'd love to have a direct line to people to help just get it possible to be usable for people so that it doesn't die before people can start using it.

**Comment by thenitai** [comment]
Are you just looking for code maintainers or someone to take over the whole project?

**Comment by whitef0x0** [comment]
@thenitai Ideally someone to take over the project. But code maintainers would help as well.

**Comment by moeffju** [comment]
@whitef0x0 Is there some way to get the project and the .com into some form of shared control? It might be hard to find someone who has a need for this project _and_ the time to maintain it, and sharing the burden might make it easier. Also things like the TLS cert being expired for months make it hard to “sell” the project…

**Comment by elioqoshi** [comment]
On a related note, is there any way we can support the project/maintainers financially?

**Comment by Leopere** [comment]
I'm actively looking for someone to look into at least making this functional and to bring up a demo instance again at the very least.

**Comment by y0va** [comment]
Is there any other instance running somewhere, to see it live?

**Comment by James9074** [comment]
I hate to say it, but I'm in the same boat... I can look into getting it fixed up but honestly I'd probably need to rewrite it in node to support it on the daily.

**Comment by Leopere** [comment]
@James9074 have you managed to get it running?  I'd love to hear your experiences and pain points so that we could potentially update and just get the Docker stuff running.  Even if it's a YMMV instance it's at least a potential way to inspire other potential contributors.

**Comment by whitef0x0** [comment]
@Leopere I fixed the docker install. You can see the new instructions on this repo's README under the docker deployment section.

**Comment by Leopere** [comment]
@whitef0x0 you are a star! <3 I can't wait for some degree of free time now to test and play!

**Comment by Leopere** [comment]
@whitef0x0 I don't have enough perms for the rest of the project unless you've pulled them for now. Now that there's a baseline for what to expect via the Docker stuff I can help out a lot more.  I've gotten the containers mostly spun up in my dev env but am blocked by the fact that I should be asleep and am in need of setting up a test user on my mail server.  I'll do this in the morning during any free time I leverage from the day.

**Comment by whitef0x0** [comment]
@Leopere I just gave you admin access to the org. Do you have namecheap? I can share admin functionality with you. Or through cloudflare

**Comment by Leopere** [comment]
@whitef0x0 contact me out of band via github-temporary@nixc.us, and I'll reply via my proper email.  I love that you use Namecheap they're great. I appreciate their company far more than the competition.  

I have a Cloudflare account but I try to avoid using middlemen organizations who are a great target for government bullying. I still don't know how much I can do here as I'm not a full stack dev but if its not offensive to have me on this thing I'm not allergic.  I mostly just want to get the Docker stuff organized in a way that makes it easier for other people to contribute test and deploy.
